services:
  uptimekuma:
    image: louislam/uptime-kuma:2.1.3
    container_name: UptimeKuma
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=UptimeKuma
    volumes:
    - ${OBSERVABILITY_PATH}/uptimekuma:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
    labels:
    - traefik.enable=true
    - traefik.docker.network=monitoring_net
    - traefik.http.routers.uptimekuma.rule=Host(`uptime.${DOMAIN}`)
    - traefik.http.routers.uptimekuma.entrypoints=web
    - traefik.http.routers.uptimekuma.middlewares=crowdsec@file
    - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/uptimekuma-icon.png
    - net.unraid.docker.webui=http://[IP]:[PORT:3002]
    networks:
    - monitoring_net
  autokuma:
    image: ghcr.io/bigboot/autokuma:2.0
    container_name: AutoKuma
    restart: unless-stopped
    environment:
    - TZ=${TZ}
    - HOST_OS=Unraid
    - HOST_HOSTNAME=JP-Dell
    - HOST_CONTAINERNAME=AutoKuma
    - AUTOKUMA__KUMA__URL=http://UptimeKuma:3001
    - AUTOKUMA__KUMA__USERNAME=${UPTIME_KUMA_USERNAME:-}
    - AUTOKUMA__KUMA__PASSWORD=${UPTIME_KUMA_PASSWORD:-}
    labels:
    - net.unraid.docker.icon=https://raw.githubusercontent.com/selfhosted/unRAID-CA-templates/master/templates/img/autokuma-icon.png
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - monitoring_net
    - db_net
    - internal_net
    - iot_net
    depends_on:
    - uptimekuma
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
networks:
  monitoring_net:
    external: true
  db_net:
    external: true
  internal_net:
    external: true
  iot_net:
    external: true
  public_net:
    external: true
